### ISSUE TITLE
Purpose of Linaro Toolchain?

### ISSUE THREAD

**Issue by ghost** [darwin-on-arm/wiki#1]
Hi all,
I noticed that the wiki states the Linaro bare metal toolchain is required to build xnu on Linux. I am just wondering:
1. Why is the toolchain needed/what is its purpose?
2. If I'm only building for x86-64 anyway, do I still need it?

**Comment by b-man** [comment]
drppublic,

The toolchain is needed to build GenericBooter. If you are compiling the kernel for x86-64, you won't need it as it won't boot with GenericBooter anyhow.

**Comment by ghost** [comment]
Ah no worries, I wondered that. I'm going to try and get a standard x86-64 build working before I make the jump to ARM. Thank you for the help.
